import { type AgentState } from './state.ts'
import { type AgentDependencies } from './deps.ts'
import { SecureGitClient } from './tools.ts'

export const createNodes = (deps: AgentDependencies) => {
  return {
    retrieveNode: async (state: AgentState): Promise<Partial<AgentState>> => {
      const git = new SecureGitClient(deps.git, state.runId)
      await git.fetch(state.repository)
      await git.checkout(state.baseSha)

      return { status: 'diagnosing' }
    },

    diagnoseNode: async (_state: AgentState): Promise<Partial<AgentState>> => {
      const logs = await deps.git.getFailureLogs()
      const diagnostics = await deps.llm.diagnose(logs)

      return { diagnostics, status: 'planning' }
    },

    planNode: async (state: AgentState): Promise<Partial<AgentState>> => {
      if (!state.diagnostics) {
        throw new Error('Diagnostics missing before planning phase')
      }
      const plan = await deps.llm.plan(state.diagnostics)

      return { plan, status: 'patching' }
    },

    patchNode: async (state: AgentState): Promise<Partial<AgentState>> => {
      if (!state.plan) {
        throw new Error('Plan missing before patching phase')
      }
      const patch = await deps.llm.patch(state.plan)
      const attemptNumber = state.attemptNumber + 1

      return { candidatePatch: patch, attemptNumber, status: 'sandboxing' }
    },

    sandboxNode: async (state: AgentState): Promise<Partial<AgentState>> => {
      if (!state.candidatePatch) {
        throw new Error('Candidate patch missing before sandbox phase')
      }

      const result = await deps.sandbox.runValidation(state.candidatePatch)
      return { sandboxResult: result }
    },

    openPrNode: async (state: AgentState): Promise<Partial<AgentState>> => {
      if (state.sandboxResult?.verdict !== 'pass') {
        throw new Error('Cannot open PR without a passing sandbox result.')
      }

      const git = new SecureGitClient(deps.git, state.runId)
      const branchName = `adamant/${state.runId}`

      await git.commit('Apply automated fix')
      await git.push(branchName)

      const prNumber = await git.openPr(
        branchName,
        state.baseSha,
        `Automated fix for ${state.runId}`,
        'Automated fix generated by Adamant.',
      )

      return { prNumber, status: 'publishing' }
    },

    mergePrNode: async (state: AgentState): Promise<Partial<AgentState>> => {
      if (!state.prNumber) {
        throw new Error('PR number missing before merge phase')
      }
      const git = new SecureGitClient(deps.git, state.runId)

      try {
        await git.mergePr(state.prNumber, state.prNumber, state.sandboxResult?.verdict)
        return { status: 'completed' }
      } catch (err) {
        const message = err instanceof Error ? err.message : String(err)
        return { error: message, status: 'failed' }
      }
    },
  }
}
